### ISSUE TITLE
CPU temperature & fan speed

### ISSUE THREAD

**Issue by igorpetrov** [advancingu/XPS13Linux#23]
I want to apologize in advance, but this post is not about the problem but request for advice.

Remembering my previous Dell laptop the first thing I've did after installing Ubuntu was installing i8kutils driver for fan control. But my colleagues says that it's not a good idea to override default settings of temperature management. Meaning "fan were specially configured at factory for best performance and lifetime".

So what do you think, does this machine need manual fan control?

What temperature may be considered as normal for our Broadwells? I have about 50-65 Celsius degrees at i5, fan not running before reach 65 deg.

**Comment by soren121** [comment]
Those temps are perfectly fine. Broadwell can safely handle over 100C, and I've never seen the CPU temp in my XPS exceed 80C max, even when compiling the kernel for an hour on all four threads.

**Comment by advancingu** [comment]
I've been working on a XPS 13 (2015) Developer Edition machine for a few weeks now for software development on stock Ubuntu 15.04. Unless you're compiling or doing other CPU intensive tasks, the fan never turns on at all, e.g. during coding. When it does turn on, it is not intrusive (and I absolutely hate fan noise).

I'll now close this since it's not an actual issue.
