### ISSUE TITLE
What relation do this Issues list and https://bugs.launchpad.net/dell-sputnik/+bugs have?

### ISSUE THREAD

**Issue by anaran** [advancingu/XPS13Linux#25]
I just found out about
https://bugs.launchpad.net/dell-sputnik/+bugs
today and was wondering whether there is a duplication on effort between it and https://github.com/advancingu/XPS13Linux/issues.

Please advise.

**Comment by advancingu** [comment]
The Launchpad tracker appears to be about the previous edition issues. The issues here are collected in an effort to find workarounds and solutions to issues with the 2015 edition.

**Comment by jared-dominguez** [comment]
@advancingu Incorrect. The dell-sputnik LP project is for all generations of the XPS 13 and M3800 Developer Editions and is managed by Canonical's OEM Solutions team, though people haven't been reporting bugs there as much lately. However, when filing bugs in Launchpad that affect the Dell Developer Edition systems, it's still recommended to file the bugs against that project (in addition to other projects as relevant, such as the linux LP project if it's a kernel bug) since it's easier for us (Dell and Canonical) to track that way.

**Comment by advancingu** [comment]
@jared-dominguez Great, so what's your plan?

**Comment by jared-dominguez** [comment]
My plan? I'm not sure what you're suggesting. My point is that the dell-sputnik LP project is still valid (answering the original question) and pointing out that it's somewhere Dell/Canonical watch.

**Comment by anaran** [comment]
@jared-dominguez how would one specify  XPS 13 (old model), XPS 13 2015, or M3800 when submitting a sputnik bug at launchpad?

@advancingu Thanks, the description of this github project mentions the 2015 model, so I guess that part is clarified. Let's see what @jared-dominguez has to say about the launchpad model classification question above.

**Comment by jared-dominguez** [comment]
@anaran There's not a specific field to specify the model. I would recommend specifying it in the bug title and description. Ideally, you would use ubuntu-bug to report the issue so as to include important system information.
